name: treecls
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.6.2=hbcca054_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libfaiss=1.7.4=cuda112hb18a002_0_cuda
  - libfaiss-avx2=1.7.4=cuda112h1234567_0_cuda
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - liblapack=3.9.0=22_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - mpi=1.0=mpich
  - mpi4py=3.1.6=py310h30280a6_0
  - mpich=4.2.1=h846660c_100
  - ncurses=6.4.20240210=h59595ed_0
  - openssl=3.3.1=h4ab18f5_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.10.14=hd12c33a_0_cpython
  - python_abi=3.10=4_cp310
  - readline=8.2=h8228510_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.10.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autopage==0.5.2
      - av==15.1.0
      - certifi==2022.12.7
      - cfgv==3.4.0
      - charset-normalizer==2.1.1
      - cliff==4.6.0
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorama==0.4.6
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - distlib==0.3.8
      - distro==1.9.0
      - einops==0.8.0
      - exceptiongroup==1.2.1
      - faiss-gpu==1.7.2
      - filelock==3.13.1
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - grad-cam==1.5.4
      - greenlet==3.0.3
      - grpcio==1.63.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - identify==2.5.36
      - idna==3.4
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - jiter==0.11.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lightning==2.2.4
      - lightning-utilities==0.11.2
      - llvmlite==0.44.0
      - loguru==0.7.3
      - mako==1.3.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiscaledeformableattention==1.0
      - networkx==3.2.1
      - nodeenv==1.8.0
      - numba==0.61.0
      - numpy==1.26.3
      - omegaconf==2.3.0
      - openai==1.108.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.10.0.84
      - optuna==2.10.1
      - packaging==24.0
      - pandas==2.2.3
      - pbr==6.0.0
      - pillow==10.2.0
      - platformdirs==4.2.1
      - pluggy==1.5.0
      - pre-commit==3.7.1
      - pretty-errors==1.2.25
      - prettytable==3.10.0
      - protobuf==5.26.1
      - psutil==7.1.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pytest==8.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.2.4
      - pytz==2025.1
      - pyyaml==6.0.1
      - qwen-vl-utils==0.0.13
      - regex==2025.9.18
      - requests==2.28.1
      - rich==13.7.1
      - rootutils==1.0.7
      - safetensors==0.4.5
      - scikit-learn==1.5.0
      - scipy==1.13.0
      - seaborn==0.13.2
      - six==1.16.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.30
      - stevedore==5.2.0
      - supervision==0.21.0
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - timm==1.0.9
      - tokenizers==0.21.4
      - tomli==2.0.1
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchmetrics==1.4.0
      - torchvision==0.16.2+cu118
      - tqdm==4.66.4
      - transformers==4.51.3
      - triton==2.1.0
      - ttach==0.0.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.1
      - urllib3==1.26.13
      - virtualenv==20.26.1
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - yarl==1.9.4
