project_name: WHU
notes: 'no inverse'
exp_name: baseline
use_wandb: False
wandb_entity: poyung
train_root: /root/data1/remote_data
val_root: /root/data1/remote_data
coarse_map: False
data_size: 384
num_workers: 4
batch_size: 16
model_name: swin-t
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0003
max_epochs: 100
warmup_batchs: 1500
use_amp: False
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 102
num_selects:
  layer1: 256
  layer2: 128
  layer3: 64
  layer4: 32
use_combiner: True
lambda_b0: 1.375
lambda_b: 0.3
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 4
log_freq: 100
eval_freq: 10
temperature: 64