project_name: WHU
exp_name: no_mask
use_wandb: False
wandb_entity: qbyjj
train_root: /root/data1/remote_data
val_root: /root/data1/remote_data
data_size: 384
num_workers: 4
batch_size: 8
model_name: lc-model
coarse_map: False
add_linear: True
use_embedding: True
no_mask: True
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0005
max_epochs: 100
warmup_batchs: 800
use_amp: False
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 102
num_classes_coarse: 10
finegrain: False
num_selects:
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 10